title: Mostafa Rezayat 
logo: /assets/img/photo.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
show_ref_links: true
cvlocation: /assets/CV_sr.pdf
email: srezayat@asu.edu
scholar: https://scholar.google.com/citations?user=bc6Gll8AAAAJ&hl=en
linkedin: https://www.linkedin.com/in/s-mostafa-rezayat-37897358/
